# Site/SEO settings
email: thomas.vaeth@gmail.com
permalink: /:year/:month/:title/
google_analytics: UA-57782903-1

name: Thomas Vaeth
title: Thomas Vaeth
description: >
  My name is Thomas Vaeth. I am front-end developer based in Seattle, Washington. I currently work at Redfin and have previously worked at Urban Influence and Getty Images.
url: https://thomasvaeth.com
twitter_username: thomasvaeth
default_img: https://thomasvaeth.com/assets/images/me.jpg

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - CNAME
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md

# Pagination
paginate: 3
paginate_path: '/page/:num/'

# Collections
collections:
  work:
    output: true
    permalink: /:path/
